---
title: "Module04 Assignment 02"
author: "RJH"
format: html
---

## Libraries 

```{r}
library(tidyverse)
```

## Data 

RUN   ZONE    WAFER    THICKNESS

>The goal of this study is to determine if this process is capable of consistently growing oxide films with a thickness of 560 Angstroms +/- 100 Angstroms. An additional goal is to determine important sources of variation for use in the development of a process control strategy.

```{r}
furnace_names <- c("run", "zone", "wafer", "thickness")

furnace <- read_table("data/FURNACE.DAT", skip = 25, col_names = furnace_names, col_types = "iffd")

furnace
```


## Visiualization

```{r}
furnace |> 
  ggplot(aes(run, thickness)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
furnace |> 
  ggplot(aes(zone, thickness)) +
  geom_boxplot(notch = TRUE)
```

```{r}
furnace |> 
  ggplot(aes(wafer, thickness)) +
  geom_boxplot(notch = TRUE)
```
```{r}
furnace |> 
  ggplot(aes(run, thickness)) +
  geom_point() 
```


```{r}
furnace2 <- furnace |> 
  rownames_to_column() |> 
  mutate(
    week = case_when(
      run <= 7 ~ "Week 01",
      run > 7 & run <= 14 ~ "Week 02",
      run > 14 ~ "Week 03"
    )
  )

furnace2
```



```{r}
furnace2 |> 
  ggplot(aes(run, thickness)) +
  geom_point() +
  geom_smooth(aes(color = week), method = "lm") +
  geom_hline(yintercept = 560) + 
  geom_hline(yintercept = c(560 + 100, 560 -100),  color = "red", linetype = "dashed")
```








